=== svhi/BioDivAppConfigEditor/src/main/webapp/assets/xml-configs/configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="edu.hsb.biodivapp" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="configuration" type="edu:configurationType" xmlns:edu="edu.hsb.biodivapp"/>
    <xs:complexType name="configurationType" mixed="true">
        <xs:sequence>
            <xs:element type="edu:locale" name="defaultLanguage" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:mapType" name="map" minOccurs="0" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:singleSubmitType" name="singleSubmit" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:multiSubmitType" name="multiSubmit" minOccurs="0" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType>

    <!-- basic elements <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<-->
    <xs:complexType name="mapType"> <!-- not supported yet -->
        <xs:sequence>
            <xs:element type="xs:string" name="option1"/>
            <xs:element type="xs:string" name="option2"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="singleSubmitType">
        <xs:sequence>
            <xs:element type="edu:entryGroupType" name="entryGroup" minOccurs="1" maxOccurs="unbounded" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="logType"> 
        <xs:sequence>
            <xs:element type="xs:boolean" name="show" minOccurs="1" maxOccurs="1"  xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="xs:integer" name="rowCount"  default="3" minOccurs="0" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="multiSubmitType"> 
        <xs:sequence>
            <xs:element type="edu:logType" name="log" minOccurs="0" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:restidMultiType" name="summerizeDataBy" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:entryGroupType" name="entryGroup" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType>

    <!--entryGroup-->
    <xs:complexType name="entryGroupType">
        <xs:sequence>
            <xs:element type="edu:labelsType" name="labels" xmlns:edu="edu.hsb.biodivapp" minOccurs="1" maxOccurs="1" />
            <xs:element type="edu:entryType" name="entry" minOccurs="1" maxOccurs="unbounded" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType>
    <!-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>-->


    <!--entry-->
    <xs:complexType name="entryType">
        <xs:sequence>
            <xs:element type="xs:boolean" name="mandatory" minOccurs="0" maxOccurs="1" default="true"/>
            <xs:element type="edu:labelsType" name="labels" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:viewportType" name="viewport" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
        <xs:attribute type="xs:ID" name="restid" use="required"/>
    </xs:complexType>


    <xs:complexType name="viewportType">
        <xs:choice>
            <xs:element type="edu:spinnerType" name="spinner" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="xs:string" name="textfield" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:numerictextfieldType" name="numerictextfield" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:buttonmatrixType" name="buttonmatrix" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:numberpickerType" name="numberpicker" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:choice>
    </xs:complexType>

    <!-- viewportTypes <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< -->
    <xs:complexType name="spinnerType">
        <xs:sequence>
            <xs:element type="edu:datasourceType" name="datasource" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType>

    <!--<xs:complexType name="textfieldType">
        <xs:sequence>
            <xs:element type="xs:int" name="decimalplaces"/>
            <xs:element type="edu:datasourceType" name="datasource" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType> -->

    <xs:complexType name="numerictextfieldType">
        <xs:sequence>
            <xs:element type="xs:nonNegativeInteger" name="decimalplaces" minOccurs="0" maxOccurs="1" default="2"/>
            <xs:element type="xs:nonNegativeInteger" name="min" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:nonNegativeInteger" name="max" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="buttonmatrixType">
        <xs:sequence>
            <xs:element type="xs:positiveInteger" name="numberOfButtons" minOccurs="0" maxOccurs="1"  default="8"/>
            <xs:element type="edu:datasourceType" name="datasource" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="numberpickerType">
        <xs:sequence>
            <xs:element type="xs:int" name="decimalplaces" minOccurs="0" maxOccurs="1" default="2"/>
            <xs:element type="xs:nonNegativeInteger" name="min" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:nonNegativeInteger" name="max" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <!-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>-->

    <xs:complexType name="datasourceType">
        <xs:sequence>
            <xs:element name="orderby" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp" default="none">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="asc"/>
                        <xs:enumeration value="desc"/>
                        <xs:enumeration value="none"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="edu:optionsType" name="options" minOccurs="1" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
            <xs:element type="edu:defaultsType" name="defaults" minOccurs="0" maxOccurs="1" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="local"/>
                    <xs:enumeration value="rest"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <!-- datasource definitions <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<-->
    <xs:complexType name="optionsType">
        <xs:choice>
            <xs:element name="uri" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:anyURI">
                        <xs:enumeration value="/rest/sourcetypes"/>
                        <xs:enumeration value="/rest/recordqualities"/>
                        <xs:enumeration value="/rest/countries"/>
                        <xs:enumeration value="/rest/species"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="edu:optionType" name="option" minOccurs="1" maxOccurs="unbounded" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="optionType">
        <xs:sequence>
            <xs:element type="xs:NCName" name="key"/>
            <xs:element type="edu:labelsType" name="labels" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="defaultsType">
        <xs:sequence>
            <xs:element type="xs:string" name="default" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>-->

    <!-- labels <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<-->
    <xs:complexType name="labelsType">
        <xs:sequence>
            <xs:element type="edu:labelType" name="label" minOccurs="1" maxOccurs="unbounded" xmlns:edu="edu.hsb.biodivapp"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="labelType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="edu:locale" name="lang" use="required" xmlns:edu="edu.hsb.biodivapp"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="locale">
        <xs:restriction base="xs:token">
            <xs:pattern
                    value="[a-zA-Z]{1,8}(_[a-zA-Z0-9]{1,8})*"
                    id="locale.pattern">
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <!-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>-->

    <xs:simpleType name="restidSingleType">
        <xs:restriction base="xs:token">
            <xs:pattern
                    value="sampling(.[a-zA-Z])+"
                    id="restidSingle.pattern">
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="restidMultiType">
        <xs:restriction base="xs:token">
            <xs:pattern
                    value="sampling.record(.[a-zA-Z])+"
                    id="restidMulti.pattern">
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== svhi/BioDivAppConfigEditor/src/main/resources/xml-configs/simpleConfig.xml
<?xml version="1.0" encoding="utf-8"?>

<configuration
        xmlns="edu.hsb.biodivapp"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="edu.hsb.biodivapp http://atlas.winkler-biologie.de/rest/schemes/configuration.xsd">
    <defaultLanguage>de</defaultLanguage>
    <!--
    <location>
         <option1></option1>
        <option2>...</option2>
    </location>
    -->
    <singleSubmit>
        <entryGroup>
            <labels>
                <label lang="de">Allgemein I</label>
                <label lang="en">General I</label>
            </labels>
            <entry restid="species">
                <labels>
                    <label lang="de">Spezies</label>
                    <label lang="en">Species</label>
                </labels>
                <viewport>
                    <spinner>
                        <datasource type="rest">
                            <orderby>asc</orderby>
                            <options>
                                <uri>/rest/species</uri>
                            </options>
                        </datasource>
                    </spinner>
                </viewport>
            </entry>
            <entry restid="color">
                <labels>
                    <label lang="de">Farbe</label>
                    <label lang="en">Color</label>
                </labels>
                <viewport>
                    <spinner>
                        <datasource type="local">
                            <orderby>none</orderby>
                            <options>
                                <option>
                                    <key>blue</key>
                                    <labels>
                                        <label lang="de">blau</label>
                                        <label lang="en_GB">blue</label>
                                    </labels>
                                </option>
                                <option>
                                    <key>red</key>
                                    <labels>
                                        <label lang="de">rot</label>
                                        <label lang="en_GB">red</label>
                                    </labels>
                                </option>
                                <option>
                                    <key>yellow</key>
                                    <labels>
                                        <label lang="de">gelb</label>
                                        <label lang="en_GB">yellow</label>
                                    </labels>
                                </option>
                            </options>
                            <defaults>
                                  <default>blue</default>
                            </defaults>
                        </datasource>
                    </spinner>
                </viewport>
            </entry>
            <entry restid="length">
                <labels>
                    <label lang="de">LÃ¤nge</label>
                    <label lang="en">Length</label>
                </labels>
                <viewport>
                    <textfield/>
                </viewport>
            </entry>
        </entryGroup>
        <entryGroup>
            <labels>
                <label lang="de">Allgemein II</label>
                <label lang="en">General II</label>
            </labels>
            <entry restid="comment">
                <mandatory>false</mandatory>
                <labels>
                    <label lang="de">Kommentar</label>
                    <label lang="en">Comment</label>
                </labels>
                <viewport>
                    <textfield/>
                </viewport>
            </entry>
        </entryGroup>
    </singleSubmit>

    <multiSubmit>
        <log>
            <show>true</show>
        </log>
        <summerizeDataBy>sampling.record.speciesid</summerizeDataBy>
        <entryGroup>
            <labels>
                <label lang="de">Mehrfach Daten</label>
                <label lang="en">Multi Data</label>
            </labels>
            <entry restid="sampling.record.speciesid">
                <labels>
                    <label lang="de">Spezies</label>
                    <label lang="en">Species</label>
                </labels>
                <viewport>
                    <buttonmatrix>
                        <numberOfButtons>9</numberOfButtons>
                        <datasource type="rest">
                            <orderby>asc</orderby>
                            <options>
                                <uri>/rest/species</uri>
                            </options>
                        </datasource>
                    </buttonmatrix>
                </viewport>
            </entry>
        </entryGroup>
    </multiSubmit>

</configuration>

=== svhi/BioDivAppConfigEditor/src/main/resources/xml-configs/Einzeldatenerfassung.xml
<?xml version="1.0" encoding="utf-8"?>

<configuration
        xmlns="edu.hsb.biodivapp"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="edu.hsb.biodivapp http://atlas.winkler-biologie.de/rest/schemes/configuration.xsd">
    <!--xsi:schemaLocation="edu.hsb.biodivapp /edu/hsbremen/biodivapp/configuration/configuration.xsd">-->

    <defaultLanguage>de</defaultLanguage>
    <!--
    <map>
         <option1>...</option1>
        <option2>...</option2>
    </map>  -->

    <singleSubmit>
        <entryGroup>
            <labels>
                <label lang="de">Allgemein</label>
                <label lang="en">General</label>
            </labels>

            <entry restid="sampling.sourcetypeid">
                <labels>
                    <label lang="de">Art der Quelle</label>
                    <label lang="en">Sourcetype</label>
                </labels>
                <viewport>
                    <spinner>
                        <datasource type="rest">
                            <orderby>asc</orderby>
                            <options>
                                <uri>/rest/sourcetypes</uri>
                            </options>
                        </datasource>
                    </spinner>
                </viewport>
            </entry>

            <entry restid="sampling.recordqualityid">
                <labels>
                    <label lang="de">Qualität des Fundes</label>
                    <label lang="en">Recordquality</label>
                </labels>
                <viewport>
                    <spinner>
                        <datasource type="rest">
                            <orderby>asc</orderby>
                            <options>
                                <uri>/rest/recordqualities</uri>
                            </options>
                        </datasource>
                    </spinner>
                </viewport>
            </entry>

            <entry restid="sampling.location.countryid">
                <labels>
                    <label lang="de">Land</label>
                    <label lang="en">Country</label>
                </labels>
                <viewport>
                    <spinner>
                        <datasource type="rest">
                            <orderby>asc</orderby>
                            <options>
                                <uri>/rest/countries</uri>
                            </options>
                            <defaults>
                                <default>DE</default>
                            </defaults>
                        </datasource>
                    </spinner>
                </viewport>
            </entry>

            <entry restid="sampling.comment">
                <mandatory>false</mandatory>
                <labels>
                    <label lang="de">Kommentar</label>
                    <label lang="en">Comment</label>
                </labels>
                <viewport>
                    <textfield/>
                </viewport>
            </entry>

            <entry restid="sampling.reference">
                <labels>
                    <label lang="de">Referenz</label>
                    <label lang="en">Reference</label>
                </labels>
                <viewport>
                    <textfield/>
                </viewport>
            </entry>
        </entryGroup>

        <entryGroup>
            <labels>
                <label lang="de">Fund-Informationen</label>
                <label lang="en">Record Information</label>
            </labels>

            <entry restid="sampling.record.speciesid">
                <labels>
                    <label lang="de">Spezies</label>
                    <label lang="en">Species</label>
                </labels>
                <viewport>
                    <buttonmatrix>
                        <numberOfButtons>10</numberOfButtons>
                        <datasource type="rest">
                            <orderby>asc</orderby>
                            <options>
                                <uri>/rest/species</uri>
                            </options>
                        </datasource>
                    </buttonmatrix>
                </viewport>
            </entry>

            <entry restid="sampling.record.additionalproperties.length">
                <mandatory>false</mandatory>
                <labels>
                    <label lang="de">Totallänge in cm</label>
                    <label lang="en">Total Length in cm</label>
                </labels>
                <viewport>
                    <numerictextfield>
                        <decimalplaces>2</decimalplaces>
                        <min>0</min>
                        <max>1000</max>
                    </numerictextfield>
                </viewport>
            </entry>



            <!--<entry restid="sampling.record.additionalproperties.sex">
                <labels>
                    <label lang="de">Geschlecht</label>
                    <label lang="en">Sex</label>
                </labels>
                <viewport>
                    <spinner>
                        <datasource type="local">
                            <orderby>none</orderby>
                            <options>
                                <option>
                                    <key>unknown</key>
                                    <labels>
                                        <label lang="de">unbekannt</label>
                                        <label lang="en">unkown</label>
                                    </labels>
                                </option>
                                <option>
                                    <key>male</key>
                                    <labels>
                                        <label lang="de">männlich</label>
                                        <label lang="en">male</label>
                                    </labels>
                                </option>
                                <option>
                                    <key>female</key>
                                    <labels>
                                        <label lang="de">weiblich</label>
                                        <label lang="en">female</label>
                                    </labels>
                                </option>
                            </options>
                            <defaults>
                                <default>unknown</default>
                            </defaults>
                        </datasource>
                    </spinner>
                </viewport>
            </entry>
            -->

            <entry restid="sampling.record.comment">
                <mandatory>false</mandatory>
                <labels>
                    <label lang="de">Kommentar zum Fund</label>
                    <label lang="en">Comment for Record</label>
                </labels>
                <viewport>
                    <textfield/>
                </viewport>
            </entry>

        </entryGroup>
    </singleSubmit>
</configuration>
